import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({
  variable: '--font-sans',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: "Pharma Cube",
  description: "Generated by create next app",
  icons: "/logo.png",
  manifest: "/pharmacube.webmanifest",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  userScalable: false,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#101828" },
    { media: "(prefers-color-scheme: dark)", color: "#101828" }
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", inter.className)}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
